### ISSUE TITLE
FIDO test app Opera browser - authenticatorAttachment error

### ISSUE THREAD

**Issue by kopovan** [wultra/powerauth-server#1436] opened 2024-03-28 08:54 UTC
1. First I have registred a new user
2. Before logging in I have changed the "User Verification" to "preferred" -> see error message

<img src="https://github.com/wultra/powerauth-server/assets/135111051/2e36dd84-86a6-49de-a6c8-47b9aec60091" width="300" />

**Comment by jnpsk** [comment] 2024-03-28 09:01
That is a validation error caused by Non Blank constraint on `AssertionVerificationRequest#authenticatorAttachment`. According to the [WebAuthn spec](https://w3c.github.io/webauthn/#iface-pkcredential), the `authenticatorAttachment` is nullable. This should be fixed also in `AuthenticatorParameters`.

**Closed** 2024-03-28 13:17 UTC

**Comment by kopovan** [comment] 2024-04-02 10:01
retest ok
