### ISSUE TITLE
Use single technology instead of Spring WS and Axis2 for SOAP clients

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-server#114] opened 2018-06-21 21:47 UTC
We currently have unnecessary fragmentation of SOAP technologies. By having only one client, we could greatly simplify some of the code in `powerauth-restful-integration`, as well as make the whole software a bit more manageable (less components) and less issue prune (we are waiting for ages for Axis2 in 1.8.0 version which fixes #2).

The change will impact following almost all projects (since they use SOAP clients here and there):

- `powerauth-restful-integration`
- `powerauth-admin`
- `powerauth-push-server`
- `powerauth-webflow`

Note that this change will have quite an impact on documentation...

**Comment by petrdvorak** [comment] 2018-06-21 21:51
_note: Let's build a simple command-line testing app to validate wsimport, Spring WS, Axis2, Apache CFX, ... implementations and chose the best._

**Comment by petrdvorak** [comment] 2018-08-31 17:09
_note2: Let's not build a simple command-line testing app and let's dive into Spring WS only. It seems that the library itself is very lightweight, see the resulting build artifact size._

<img width="772" alt="screen shot 2018-08-31 at 19 06 59" src="https://user-images.githubusercontent.com/516597/44926320-53854800-ad51-11e8-9397-540408a31c26.png">

**Comment by petrdvorak** [comment] 2018-11-28 17:48
And so it happened, time solved this one for us. All our customers agreed that REST is a preferred technology. We will rewrite `restful-integration` projects to use REST in the next release.

**Comment by romanstrobl** [comment] 2019-05-02 12:19
This issue will have to be postponed to the next release.

**Comment by romanstrobl** [comment] 2020-07-16 09:33
The restful-integration project has been migrated to the REST client for Spring. For the Java EE part we will still use Axis2 with the plan to drop it when Java EE is no longer used and all clients migrate to Spring. The Axis2 client has been marked as deprecated.

**Comment by romanstrobl** [comment] 2020-08-03 16:26
The issue is resolved now.

**Closed by romanstrobl** 2020-08-03 16:26 UTC
Labels: enhancement, next
